name: Build and Upload SDK

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout. Defaults to the ref that triggered the workflow."
        required: false
        type: string
      runs-on:
        description: "JSON array of runner labels."
        required: false
        type: string
        default: '["self-hosted","linux","jammy","x64","xlarge"]'
      platforms:
        description: 'JSON array of platforms, e.g. ["amd64","arm64","riscv64"]'
        required: true
        type: string
      platform-flag:
        description: "Flag passed to sdkcraft pack: --build-for or --platform"
        required: false
        type: string
        default: "--build-for"
      track:
        description: "Release track to upload to (e.g. 1.24). Defaults to the branch name."
        required: false
        type: string
      risk:
        description: "Risk level to release to (e.g. edge, beta, stable)."
        required: false
        type: string
        default: "edge"
    secrets:
      SDKCRAFT_STORE_CREDENTIALS:
        required: true

jobs:
  build-and-upload:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    strategy:
      matrix:
        platform: ${{ fromJSON(inputs.platforms) }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Install sdkcraft
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          max_attempts: 3
          retry_wait_seconds: 60
          timeout_minutes: 10
          command: sudo snap install sdkcraft --edge --classic

      - name: Define the track name to upload to
        run: |
          if [ -n "${{ inputs.track }}" ]; then
            TRACK="${{ inputs.track }}"
          elif [ -n "${{ github.event.inputs.branch }}" ]; then
            TRACK="${{ github.event.inputs.branch }}"
          else
            TRACK="${GITHUB_REF#refs/heads/}"
          fi
          echo "TRACK=$TRACK" >> $GITHUB_ENV

      - name: Pack SDK for ${{ matrix.platform }}
        # use a third-party retry as we cannot fetch a helper from this private repo
        # in the context of another repo's workflow.
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          max_attempts: 3
          retry_wait_seconds: 60
          timeout_minutes: 120
          command: sdkcraft pack ${{ inputs.platform-flag }} ${{ matrix.platform }}

      - name: Upload SDK for ${{ matrix.platform }}
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        env:
          SDKCRAFT_STORE_CREDENTIALS: ${{ secrets.SDKCRAFT_STORE_CREDENTIALS }}
        with:
          max_attempts: 3
          retry_wait_seconds: 3600 # 1 hour
          timeout_minutes: 10
          command: sdkcraft upload *.sdk --release ${{ env.TRACK }}/${{ inputs.risk }}
